import {
  LiveFlowItem,
  NewsFlowItem,
  InsiderFlowItem,
  CongressFlowItem,
  FlowSummary,
  FlowFilterConfig,
  SavedFilterPreset,
  FlowLeaderboardItem,
} from "./types";

export const DEFAULT_SAVED_PRESETS: SavedFilterPreset[] = [
  {
    id: "yolos",
    name: "YOLOs",
    tagline: "High risk, high reward trades",
    color: "orange",
    tags: ["< 3 days", "Bullish or bearish", "Buy side only", "Chance < 20%"],
    config: {
      maxDte: 3,
      sides: ["BUY"],
      chanceOperator: "less_than",
      chanceValue: 20,
    },
  },
  {
    id: "in_the_know",
    name: "In The Know",
    tagline: "Someone knows something",
    color: "cyan",
    tags: ["< 14 days", "Bullish or bearish", "Buy side only", "Stocks only", "Small-cap only", "Vol > OI"],
    config: {
      maxDte: 14,
      sides: ["BUY"],
      assetTypes: ["stock"],
      marketCaps: ["small"],
      volOverOiOnly: true,
    },
  },
  {
    id: "highly_unusual",
    name: "Highly Unusual",
    tagline: "Large trades with high volume",
    color: "magenta",
    tags: ["> $1.00m", "Vol > OI"],
    config: {
      minPremium: 1000000,
      volOverOiOnly: true,
    },
  },
  {
    id: "ai_stocks",
    name: "AI Stocks",
    tagline: "Semiconductors & Generative AI ecosystem",
    color: "cyan",
    tags: ["NVDA", "TSM", "AMD", "META", "AI", "GOOGL"],
    config: {
      tickers: ["NVDA", "TSM", "AMD", "META", "AI", "GOOGL", "GOOG", "AMZN", "MSFT"],
    },
  },
  {
    id: "large_trades",
    name: "Large Trades",
    tagline: "Institutional million-dollar blocks",
    color: "yellow",
    tags: ["> $1.00m", "C-Suite Insiders"],
    config: {
      minPremium: 1000000,
    },
  },
];

export const DEFAULT_FILTER_CONFIG: FlowFilterConfig = {
  tickers: [],
  minPremium: 0,
  maxDte: 9999,
  sentiments: ["bullish", "bearish", "neutral"],
  sides: ["BUY", "SELL"],
  orderTypes: ["SWEEP", "SPLIT", "BLOCK", "SINGLE"],
  assetTypes: ["stock", "etf"],
  marketCaps: ["small", "mid", "large"],
  contractTypes: ["calls", "puts", "spreads"],
  isOtmOnly: false,
  volOverOiOnly: false,
  upcomingEarningsOnly: false,
  aboveAskBelowBidOnly: false,
  priceOperator: "less_than",
  priceValue: null,
  chanceOperator: "less_than",
  chanceValue: null,
  insiderNames: [],
  congressChamber: "all",
  congressParty: "all",
};

export const RAW_LIVE_FLOW_ITEMS: LiveFlowItem[] = [
  // WMT Active & Historical trades (Screenshots 2 & 3)
  {
    id: "wmt_flow_combo",
    time: "10/6 3:51pm",
    timestamp: 1791330660000,
    symbol: "WMT",
    companyName: "Walmart",
    underlyingPrice: 107.2,
    strategy: "Buy 97.5/135 Combo",
    strategyTitle: "WMT Long Combo",
    expiration: "Jan 15 '27",
    dte: 100,
    strike: "97.5/135",
    premium: 314000,
    premiumFormatted: "$314k",
    type: "SINGLE",
    side: "BUY",
    sentiment: "bullish",
    volume: 4603,
    openInterest: 28398,
    volOverOi: false,
    isOtm: true,
    hasEarnings: false,
    chance: 68,
    marketCap: "large",
    assetType: "stock",
    legsDetails: [
      { action: "Buy", option: "135C 1/15/27", quantity: 2000, strike: 135, optionType: "CALL", expirationDate: "2027-01-15" },
      { action: "Sell", option: "97.5P 1/15/27", quantity: 2000, strike: 97.5, optionType: "PUT", expirationDate: "2027-01-15" },
    ],
    totalQuantity: 4000,
    isCredit: true,
    creditOrDebitText: "CREDIT",
    fillPrice: 1.57,
    currentContractPrice: 1.63,
    spotAtFill: 107.36,
    currentSpot: 107.2,
    flowTypeCategory: "Single",
    performanceNow: "--% 🔒",
    performanceHigh: "--% 🔒",
    performanceLow: "--% 🔒",
    calculationText:
      "If making this trade now, you would receive a $162.50 credit. The maximum potential loss would be $9,587.50, and the maximum gain would be infinite. There is a --% 🔒 chance of profit, achieved when WMT is above $95.88 at expiry.",
    returnSinceFillText: "-$5.50 (-3.5%) return since Oct 6, 2026, 3:51 PM",
  },
  {
    id: "wmt_flow_put",
    time: "10/6 3:50pm",
    timestamp: 1791330600000,
    symbol: "WMT",
    companyName: "Walmart",
    underlyingPrice: 107.2,
    strategy: "Buy 120 Put",
    strategyTitle: "WMT Long Put",
    expiration: "Dec 18",
    dte: 72,
    strike: 120,
    premium: 113000,
    premiumFormatted: "$113k",
    type: "SPLIT",
    side: "BUY",
    sentiment: "bearish",
    volume: 2450,
    openInterest: 1800,
    volOverOi: true,
    isOtm: false,
    hasEarnings: false,
    chance: 45,
    marketCap: "large",
    assetType: "stock",
    legsDetails: [
      { action: "Buy", option: "120P 12/18", quantity: 500, strike: 120, optionType: "PUT", expirationDate: "2026-12-18" },
    ],
    totalQuantity: 500,
    isCredit: false,
    creditOrDebitText: "DEBIT",
    fillPrice: 2.26,
    currentContractPrice: 2.3,
    spotAtFill: 107.3,
    currentSpot: 107.2,
    flowTypeCategory: "Split",
  },
  {
    id: "wmt_flow_calls",
    time: "10/6 3:32pm",
    timestamp: 1791329520000,
    symbol: "WMT",
    companyName: "Walmart",
    underlyingPrice: 107.2,
    strategy: "Buy 108/115 Calls",
    strategyTitle: "WMT Bull Call Spread",
    expiration: "Oct 30 - Nov 20",
    dte: 30,
    strike: "108/115",
    premium: 89000,
    premiumFormatted: "$89k",
    type: "SINGLE",
    side: "BUY",
    sentiment: "bullish",
    volume: 3100,
    openInterest: 2200,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 55,
    marketCap: "large",
    assetType: "stock",
    legsDetails: [
      { action: "Buy", option: "108C 10/30", quantity: 600, strike: 108, optionType: "CALL", expirationDate: "2026-10-30" },
      { action: "Sell", option: "115C 11/20", quantity: 600, strike: 115, optionType: "CALL", expirationDate: "2026-11-20" },
    ],
    totalQuantity: 1200,
    isCredit: false,
    creditOrDebitText: "DEBIT",
    fillPrice: 1.48,
    currentContractPrice: 1.5,
    spotAtFill: 107.25,
    currentSpot: 107.2,
    flowTypeCategory: "Single",
  },
  {
    id: "wmt_flow_sweep",
    time: "10/6 3:12pm",
    timestamp: 1791328320000,
    symbol: "WMT",
    companyName: "Walmart",
    underlyingPrice: 107.2,
    strategy: "Sell 105 Call",
    strategyTitle: "WMT Short Call",
    expiration: "Nov 20",
    dte: 44,
    strike: 105,
    premium: 241000,
    premiumFormatted: "$241k",
    type: "SWEEP",
    side: "SELL",
    sentiment: "bearish",
    volume: 5200,
    openInterest: 3100,
    volOverOi: true,
    isOtm: false,
    hasEarnings: false,
    chance: 38,
    marketCap: "large",
    assetType: "stock",
    legsDetails: [
      { action: "Sell", option: "105C 11/20", quantity: 750, strike: 105, optionType: "CALL", expirationDate: "2026-11-20" },
    ],
    totalQuantity: 750,
    isCredit: true,
    creditOrDebitText: "CREDIT",
    fillPrice: 3.21,
    currentContractPrice: 3.15,
    spotAtFill: 107.4,
    currentSpot: 107.2,
    flowTypeCategory: "Sweep",
  },
  {
    id: "wmt_flow_block",
    time: "10/6 3:10pm",
    timestamp: 1791328200000,
    symbol: "WMT",
    companyName: "Walmart",
    underlyingPrice: 107.2,
    strategy: "Sell 115/135 Puts",
    strategyTitle: "WMT Bull Put Spread",
    expiration: "Oct 9 - Jan 15 '27",
    dte: 100,
    strike: "115/135",
    premium: 404000,
    premiumFormatted: "$404k",
    type: "BLOCK",
    side: "SELL",
    sentiment: "bullish",
    volume: 6400,
    openInterest: 4800,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 62,
    marketCap: "large",
    assetType: "stock",
    legsDetails: [
      { action: "Sell", option: "135P 1/15/27", quantity: 1000, strike: 135, optionType: "PUT", expirationDate: "2027-01-15" },
      { action: "Buy", option: "115P 10/9", quantity: 1000, strike: 115, optionType: "PUT", expirationDate: "2026-10-09" },
    ],
    totalQuantity: 2000,
    isCredit: true,
    creditOrDebitText: "CREDIT",
    fillPrice: 4.04,
    currentContractPrice: 3.9,
    spotAtFill: 107.32,
    currentSpot: 107.2,
    flowTypeCategory: "Block",
  },
  // WMT Locked items (Screenshot 2)
  { id: "wmt_lock_1", time: "10/6 3:09pm", timestamp: 1791328140000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 150000, premiumFormatted: "$150k", type: "SINGLE", side: "BUY", sentiment: "bullish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },
  { id: "wmt_lock_2", time: "10/6 2:58pm", timestamp: 1791327480000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 120000, premiumFormatted: "$120k", type: "SINGLE", side: "BUY", sentiment: "bullish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },
  { id: "wmt_lock_3", time: "10/6 2:55pm", timestamp: 1791327300000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 95000, premiumFormatted: "$95k", type: "SINGLE", side: "BUY", sentiment: "bearish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },
  { id: "wmt_lock_4", time: "10/6 2:54pm", timestamp: 1791327240000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 210000, premiumFormatted: "$210k", type: "SINGLE", side: "BUY", sentiment: "bullish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },
  { id: "wmt_lock_5", time: "10/6 2:49pm", timestamp: 1791326940000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 180000, premiumFormatted: "$180k", type: "SINGLE", side: "BUY", sentiment: "bearish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },
  { id: "wmt_lock_6", time: "10/6 2:33pm", timestamp: 1791325980000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 340000, premiumFormatted: "$340k", type: "SINGLE", side: "BUY", sentiment: "bullish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },
  { id: "wmt_lock_7", time: "10/6 2:00pm", timestamp: 1791324000000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 410000, premiumFormatted: "$410k", type: "SINGLE", side: "BUY", sentiment: "bullish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },
  { id: "wmt_lock_8", time: "10/6 1:57pm", timestamp: 1791323820000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 190000, premiumFormatted: "$190k", type: "SINGLE", side: "BUY", sentiment: "bearish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },
  { id: "wmt_lock_9", time: "10/6 1:40pm", timestamp: 1791322800000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 115000, premiumFormatted: "$115k", type: "SINGLE", side: "BUY", sentiment: "bullish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },
  { id: "wmt_lock_10", time: "10/6 1:11pm", timestamp: 1791321060000, symbol: "WMT", underlyingPrice: 107.2, strategy: "Hidden Strategy", expiration: "Nov 26", dte: 50, strike: 110, premium: 260000, premiumFormatted: "$260k", type: "SINGLE", side: "BUY", sentiment: "bearish", volume: 1000, openInterest: 1000, volOverOi: false, isOtm: true, hasEarnings: false, chance: 50, isLocked: true, marketCap: "large", assetType: "stock" },

  // Remaining institutional prints
  {
    id: "flow_1",
    time: "8:09am",
    timestamp: Date.now() - 360000,
    symbol: "XSP",
    companyName: "Mini-SPX Index",
    underlyingPrice: 586.4,
    strategy: "Buy 752 Put To Open",
    expiration: "Nov 6",
    dte: 30,
    strike: 752,
    premium: 14000,
    premiumFormatted: "$14k",
    type: "SPLIT",
    side: "BUY",
    sentiment: "bearish",
    volume: 1450,
    openInterest: 820,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 18,
    marketCap: "large",
    assetType: "etf",
  },
  {
    id: "flow_lock_1",
    time: "8:03am",
    timestamp: Date.now() - 720000,
    symbol: "SPY",
    underlyingPrice: 585.1,
    strategy: "Buy 590 Call",
    expiration: "Oct 18",
    dte: 11,
    strike: 590,
    premium: 84000,
    premiumFormatted: "$84k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bullish",
    volume: 3200,
    openInterest: 1200,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 35,
    isLocked: true,
    marketCap: "large",
    assetType: "etf",
  },
  {
    id: "flow_lock_2",
    time: "7:59am",
    timestamp: Date.now() - 960000,
    symbol: "TSLA",
    underlyingPrice: 380.6,
    strategy: "Buy 400 Call",
    expiration: "Oct 25",
    dte: 18,
    strike: 400,
    premium: 320000,
    premiumFormatted: "$320k",
    type: "BLOCK",
    side: "BUY",
    sentiment: "bullish",
    volume: 5400,
    openInterest: 2100,
    volOverOi: true,
    isOtm: true,
    hasEarnings: true,
    chance: 28,
    isLocked: true,
    marketCap: "large",
    assetType: "stock",
  },
  {
    id: "flow_lock_3",
    time: "7:58am",
    timestamp: Date.now() - 1020000,
    symbol: "NVDA",
    underlyingPrice: 233.9,
    strategy: "Buy 245 Call",
    expiration: "Oct 11",
    dte: 4,
    strike: 245,
    premium: 1250000,
    premiumFormatted: "$1.25m",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bullish",
    volume: 12400,
    openInterest: 3100,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 22,
    isLocked: true,
    marketCap: "large",
    assetType: "stock",
  },
  {
    id: "flow_2",
    time: "7:43am",
    timestamp: Date.now() - 1920000,
    symbol: "XSP",
    companyName: "Mini-SPX Index",
    underlyingPrice: 586.4,
    strategy: "Sell 773 Call To Open",
    expiration: "Oct 26",
    dte: 19,
    strike: 773,
    premium: 13000,
    premiumFormatted: "$13k",
    type: "SPLIT",
    side: "SELL",
    sentiment: "bearish",
    volume: 980,
    openInterest: 1100,
    volOverOi: false,
    isOtm: true,
    hasEarnings: false,
    chance: 12,
    marketCap: "large",
    assetType: "etf",
  },
  {
    id: "flow_3",
    time: "10/6 4:12pm",
    timestamp: Date.now() - 54000000,
    symbol: "QQQ",
    companyName: "Invesco QQQ Trust",
    underlyingPrice: 494.3,
    strategy: "Buy 755 Put",
    expiration: "Oct 7",
    dte: 1,
    strike: 755,
    premium: 51000,
    premiumFormatted: "$51k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bearish",
    volume: 4800,
    openInterest: 1100,
    volOverOi: true,
    isOtm: false,
    hasEarnings: false,
    chance: 15,
    marketCap: "large",
    assetType: "etf",
  },
  {
    id: "flow_4",
    time: "10/6 4:12pm",
    timestamp: Date.now() - 54000000,
    symbol: "QQQ",
    companyName: "Invesco QQQ Trust",
    underlyingPrice: 494.3,
    strategy: "Buy 750 Put",
    expiration: "Oct 7",
    dte: 1,
    strike: 750,
    premium: 38000,
    premiumFormatted: "$38k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bearish",
    volume: 3200,
    openInterest: 950,
    volOverOi: true,
    isOtm: false,
    hasEarnings: false,
    chance: 14,
    marketCap: "large",
    assetType: "etf",
  },
  {
    id: "flow_5",
    time: "10/6 4:11pm",
    timestamp: Date.now() - 54060000,
    symbol: "QQQ",
    companyName: "Invesco QQQ Trust",
    underlyingPrice: 494.3,
    strategy: "Buy 750 Put",
    expiration: "Oct 7",
    dte: 1,
    strike: 750,
    premium: 95000,
    premiumFormatted: "$95k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bearish",
    volume: 7100,
    openInterest: 1200,
    volOverOi: true,
    isOtm: false,
    hasEarnings: false,
    chance: 14,
    marketCap: "large",
    assetType: "etf",
  },
  {
    id: "flow_6",
    time: "10/6 4:08pm",
    timestamp: Date.now() - 54240000,
    symbol: "QQQ",
    companyName: "Invesco QQQ Trust",
    underlyingPrice: 494.3,
    strategy: "Buy 755 Put",
    expiration: "Oct 7",
    dte: 1,
    strike: 755,
    premium: 63000,
    premiumFormatted: "$63k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bearish",
    volume: 5100,
    openInterest: 1100,
    volOverOi: true,
    isOtm: false,
    hasEarnings: false,
    chance: 15,
    marketCap: "large",
    assetType: "etf",
  },
  {
    id: "flow_7",
    time: "10/6 4:00pm",
    timestamp: Date.now() - 54720000,
    symbol: "QQQ",
    companyName: "Invesco QQQ Trust",
    underlyingPrice: 494.3,
    strategy: "Buy 750 Put",
    expiration: "Oct 9",
    dte: 3,
    strike: 750,
    premium: 154000,
    premiumFormatted: "$154k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bearish",
    volume: 9800,
    openInterest: 1450,
    volOverOi: true,
    isOtm: false,
    hasEarnings: false,
    chance: 16,
    marketCap: "large",
    assetType: "etf",
  },
  {
    id: "flow_8",
    time: "10/6 3:55pm",
    timestamp: Date.now() - 55020000,
    symbol: "NVDA",
    companyName: "NVIDIA Corporation",
    underlyingPrice: 233.95,
    strategy: "Buy 232.5 Put",
    expiration: "Oct 9",
    dte: 3,
    strike: 232.5,
    premium: 55000,
    premiumFormatted: "$55k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bearish",
    volume: 4200,
    openInterest: 1800,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 19,
    marketCap: "large",
    assetType: "stock",
  },
  {
    id: "flow_9",
    time: "10/6 3:55pm",
    timestamp: Date.now() - 55020000,
    symbol: "IWM",
    companyName: "iShares Russell 2000 ETF",
    underlyingPrice: 221.8,
    strategy: "Buy 285 Call",
    expiration: "Oct 9",
    dte: 3,
    strike: 285,
    premium: 103000,
    premiumFormatted: "$103k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bullish",
    volume: 8500,
    openInterest: 2100,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 17,
    marketCap: "large",
    assetType: "etf",
  },
  {
    id: "flow_10",
    time: "10/6 3:53pm",
    timestamp: Date.now() - 55140000,
    symbol: "SPCH",
    companyName: "Super Micro Computer Inc",
    underlyingPrice: 28.5,
    strategy: "23/24 Bear Put Spread",
    expiration: "Oct 9",
    dte: 3,
    strike: "23/24",
    premium: 35000,
    premiumFormatted: "$35k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bearish",
    abnormalActivity: true,
    volume: 6200,
    openInterest: 1100,
    volOverOi: true,
    isOtm: true,
    hasEarnings: true,
    chance: 18,
    marketCap: "mid",
    assetType: "stock",
  },
  {
    id: "flow_11",
    time: "10/6 3:53pm",
    timestamp: Date.now() - 55140000,
    symbol: "SOXL",
    companyName: "Direxion Daily Semiconductor Bull 3X",
    underlyingPrice: 38.2,
    strategy: "Buy 170 Call",
    expiration: "Oct 7",
    dte: 1,
    strike: 170,
    premium: 67000,
    premiumFormatted: "$67k",
    type: "SPLIT",
    side: "BUY",
    sentiment: "bullish",
    volume: 3800,
    openInterest: 1200,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 12,
    marketCap: "mid",
    assetType: "etf",
  },
  {
    id: "flow_12",
    time: "10/6 3:52pm",
    timestamp: Date.now() - 55200000,
    symbol: "NVDA",
    companyName: "NVIDIA Corporation",
    underlyingPrice: 233.95,
    strategy: "Buy 242.5 Call",
    expiration: "Oct 7",
    dte: 1,
    strike: 242.5,
    premium: 97000,
    premiumFormatted: "$97k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bullish",
    volume: 7400,
    openInterest: 2300,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 19,
    marketCap: "large",
    assetType: "stock",
  },
  {
    id: "flow_13",
    time: "10/6 3:49pm",
    timestamp: Date.now() - 55380000,
    symbol: "AAPL",
    companyName: "Apple Inc.",
    underlyingPrice: 232.5,
    strategy: "Buy 340 Call",
    expiration: "Oct 9",
    dte: 3,
    strike: 340,
    premium: 34000,
    premiumFormatted: "$34k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bullish",
    volume: 2900,
    openInterest: 800,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 10,
    marketCap: "large",
    assetType: "stock",
  },
  {
    id: "flow_lock_4",
    time: "10/6 3:48pm",
    timestamp: Date.now() - 55440000,
    symbol: "AMZN",
    underlyingPrice: 186.5,
    strategy: "Buy 190 Call",
    expiration: "Oct 18",
    dte: 12,
    strike: 190,
    premium: 450000,
    premiumFormatted: "$450k",
    type: "BLOCK",
    side: "BUY",
    sentiment: "bullish",
    volume: 5100,
    openInterest: 1800,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 38,
    isLocked: true,
    marketCap: "large",
    assetType: "stock",
  },
  {
    id: "flow_lock_5",
    time: "10/6 3:46pm",
    timestamp: Date.now() - 55560000,
    symbol: "AMD",
    underlyingPrice: 172.4,
    strategy: "Buy 160 Put",
    expiration: "Oct 25",
    dte: 19,
    strike: 160,
    premium: 210000,
    premiumFormatted: "$210k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bearish",
    volume: 3800,
    openInterest: 1100,
    volOverOi: true,
    isOtm: true,
    hasEarnings: true,
    chance: 25,
    isLocked: true,
    marketCap: "large",
    assetType: "stock",
  },
  {
    id: "flow_lock_6",
    time: "10/6 3:44pm",
    timestamp: Date.now() - 55680000,
    symbol: "META",
    underlyingPrice: 588.6,
    strategy: "Buy 600 Call",
    expiration: "Nov 1",
    dte: 26,
    strike: 600,
    premium: 1850000,
    premiumFormatted: "$1.85m",
    type: "BLOCK",
    side: "BUY",
    sentiment: "bullish",
    volume: 3200,
    openInterest: 850,
    volOverOi: true,
    isOtm: true,
    hasEarnings: true,
    chance: 42,
    isLocked: true,
    marketCap: "large",
    assetType: "stock",
  },
  {
    id: "flow_14",
    time: "10/6 3:40pm",
    timestamp: Date.now() - 55920000,
    symbol: "ASTS",
    companyName: "AST SpaceMobile, Inc.",
    underlyingPrice: 26.8,
    strategy: "Buy 30 Call",
    expiration: "Oct 11",
    dte: 5,
    strike: 30,
    premium: 78000,
    premiumFormatted: "$78k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bullish",
    volume: 9100,
    openInterest: 1600,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 24,
    marketCap: "small",
    assetType: "stock",
  },
  {
    id: "flow_15",
    time: "10/6 3:35pm",
    timestamp: Date.now() - 56220000,
    symbol: "PLTR",
    companyName: "Palantir Technologies",
    underlyingPrice: 43.5,
    strategy: "Buy 45 Call",
    expiration: "Oct 18",
    dte: 12,
    strike: 45,
    premium: 124000,
    premiumFormatted: "$124k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bullish",
    volume: 14200,
    openInterest: 4100,
    volOverOi: true,
    isOtm: true,
    hasEarnings: false,
    chance: 31,
    marketCap: "mid",
    assetType: "stock",
  },
  {
    id: "flow_16",
    time: "10/6 3:30pm",
    timestamp: Date.now() - 56520000,
    symbol: "SMCI",
    companyName: "Super Micro Computer",
    underlyingPrice: 47.1,
    strategy: "Buy 40 Put",
    expiration: "Oct 18",
    dte: 12,
    strike: 40,
    premium: 310000,
    premiumFormatted: "$310k",
    type: "SWEEP",
    side: "BUY",
    sentiment: "bearish",
    volume: 8700,
    openInterest: 2300,
    volOverOi: true,
    isOtm: true,
    hasEarnings: true,
    chance: 28,
    marketCap: "mid",
    assetType: "stock",
  },
];

export const RAW_NEWS_FLOW_ITEMS: NewsFlowItem[] = [
  {
    id: "news_1",
    time: "8:01am",
    timestamp: Date.now() - 480000,
    headline: "Google, Unity Collaborate For New, Integrated Gaming Platform To Be Launched Later In 2026",
    symbols: ["U", "GOOG", "GOOGL"],
    source: "Bloomberg Terminal",
    sentiment: "bullish",
  },
  {
    id: "news_2",
    time: "6:58am",
    timestamp: Date.now() - 4260000,
    headline: "Nebius Group Stock Is Falling Wednesday: What's Going On?",
    symbols: ["NBIS", "NVDA", "NBIG"],
    source: "Benzinga Newsdesk",
    sentiment: "bearish",
  },
  {
    id: "news_3",
    time: "6:19am",
    timestamp: Date.now() - 6600000,
    headline: "Anthropic CEO Dario Amodei Took Home $18 Million in 2025 — How His Pay Compares With Google and Amazon CEOs: Report",
    symbols: ["AMZN", "GOOGL", "GOOG", "NVDA", "ORCL"],
    source: "Wall Street Journal",
    sentiment: "neutral",
  },
  {
    id: "news_4",
    time: "6:02am",
    timestamp: Date.now() - 7620000,
    headline: "Meta, OpenAI and Anthropic Could Become Biotech Companies, Says Stanford Neuroscientist Andrew Huberman: 'Sounds Kind of Science Fiction'",
    symbols: ["META"],
    source: "Reuters Technology",
    sentiment: "bullish",
  },
  {
    id: "news_5",
    time: "5:35am",
    timestamp: Date.now() - 9240000,
    headline: "Paul Krugman Says AI Boom Is 'Crowding Out' Other Investments in a Way the Dot-Com Era Never Did: 'This Isn't a Hypothetical Risk'",
    symbols: ["SPY", "AMZN", "GOOGL", "GOOG", "QQQ"],
    source: "New York Times Financial",
    sentiment: "bearish",
  },
  {
    id: "news_6",
    time: "5:18am",
    timestamp: Date.now() - 10260000,
    headline: "The Emmys Are Moving to Amazon Prime Video — And You Won't Need a Prime Subscription to Watch",
    symbols: ["AMZN", "GOOGL", "GOOG", "NFLX", "CMCSA"],
    source: "Variety",
    sentiment: "bullish",
  },
  {
    id: "news_7",
    time: "4:52am",
    timestamp: Date.now() - 11820000,
    headline: "Ray Dalio Says AI Bubble Is 'Close' to Bursting as Debt and Rising Rates Raise Red Flags",
    symbols: ["NVDA", "AAPL", "META", "AMZN", "GOOGL", "GOOG", "MSFT", "ORCL"],
    source: "Financial Times",
    sentiment: "bearish",
  },
  {
    id: "news_8",
    time: "3:41am",
    timestamp: Date.now() - 16080000,
    headline: "Jim Cramer Predicts Elon Musk-Led SpaceX's Next Cash Cow Raking in $4 Billion a Month as SPCX Seeks $40 Billion for NVDA Chips",
    symbols: ["SPCX", "GOOGL", "GOOG", "NVDA"],
    source: "CNBC Squawk Box",
    sentiment: "bullish",
  },
  {
    id: "news_lock_1",
    time: "3:40am",
    timestamp: Date.now() - 16140000,
    headline: "Apple M5 Ultra Architecture Leaks Point to Massive 50% AI Core Efficiency Increase",
    symbols: ["AAPL", "TSM"],
    source: "Bloomberg",
    sentiment: "bullish",
    isLocked: true,
  },
  {
    id: "news_lock_2",
    time: "3:24am",
    timestamp: Date.now() - 17100000,
    headline: "Tesla Robotaxi Fleet Begins Unsupervised Commercial Road Testing in Texas Triangle",
    symbols: ["TSLA", "UBER"],
    source: "Electrek",
    sentiment: "bullish",
    isLocked: true,
  },
  {
    id: "news_lock_3",
    time: "3:22am",
    timestamp: Date.now() - 17220000,
    headline: "Semiconductor Equipment Orders Jump 28% MoM Signaling Next CapEx Wave",
    symbols: ["ASML", "LRCX", "AMAT"],
    source: "SemiAnalysis",
    sentiment: "bullish",
    isLocked: true,
  },
  {
    id: "news_lock_4",
    time: "3:03am",
    timestamp: Date.now() - 18360000,
    headline: "Federal Reserve Signals Rate Path Confidence as Core PCE Meets Expectations",
    symbols: ["SPY", "QQQ", "TLT"],
    source: "WSJ Macro",
    sentiment: "neutral",
    isLocked: true,
  },
];

export const RAW_INSIDER_FLOW_ITEMS: InsiderFlowItem[] = [
  {
    id: "insider_1",
    reportDate: "6:03am",
    time: "6:03am",
    timestamp: Date.now() - 7560000,
    symbol: "MTN",
    companyName: "Vail Resorts, Inc.",
    trade: "Buy MTN Share Appreciation Right",
    member: "Angela A Korch",
    title: "Executive Vice President & CFO",
    premium: 3710000,
    premiumFormatted: "$3.71m",
    shares: 22500,
    price: 164.88,
    marketCap: "mid",
    assetType: "stock",
  },
  {
    id: "insider_2",
    reportDate: "6:03am",
    time: "6:03am",
    timestamp: Date.now() - 7560000,
    symbol: "MTN",
    companyName: "Vail Resorts, Inc.",
    trade: "Buy MTN Share Appreciation Right",
    member: "Lynanne Kunkel",
    title: "Chief Human Resources Officer",
    premium: 3170000,
    premiumFormatted: "$3.17m",
    shares: 19200,
    price: 165.1,
    marketCap: "mid",
    assetType: "stock",
  },
  {
    id: "insider_3",
    reportDate: "6:03am",
    time: "6:03am",
    timestamp: Date.now() - 7560000,
    symbol: "MTN",
    companyName: "Vail Resorts, Inc.",
    trade: "Buy MTN Share Appreciation Right",
    member: "Robert A Katz",
    title: "Executive Chairperson",
    premium: 7590000,
    premiumFormatted: "$7.59m",
    shares: 46000,
    price: 165.0,
    marketCap: "mid",
    assetType: "stock",
  },
  {
    id: "insider_4",
    reportDate: "6:02am",
    time: "6:02am",
    timestamp: Date.now() - 7620000,
    symbol: "MTN",
    companyName: "Vail Resorts, Inc.",
    trade: "Buy MTN Share Appreciation Right",
    member: "Gregory Jon Sullivan",
    title: "Chief Operating Officer",
    premium: 1440000,
    premiumFormatted: "$1.44m",
    shares: 8700,
    price: 165.5,
    marketCap: "mid",
    assetType: "stock",
  },
  {
    id: "insider_5",
    reportDate: "6:02am",
    time: "6:02am",
    timestamp: Date.now() - 7620000,
    symbol: "MTN",
    companyName: "Vail Resorts, Inc.",
    trade: "Buy MTN Share Appreciation Right",
    member: "Julie A DeCecco",
    title: "General Counsel & Corporate Secretary",
    premium: 2120000,
    premiumFormatted: "$2.12m",
    shares: 12850,
    price: 164.98,
    marketCap: "mid",
    assetType: "stock",
  },
  {
    id: "insider_6",
    reportDate: "6:02am",
    time: "6:02am",
    timestamp: Date.now() - 7620000,
    symbol: "MTN",
    companyName: "Vail Resorts, Inc.",
    trade: "Buy MTN Share Appreciation Right",
    member: "Celeste Burgoyne",
    title: "Director",
    premium: 7060000,
    premiumFormatted: "$7.06m",
    shares: 42800,
    price: 164.95,
    marketCap: "mid",
    assetType: "stock",
  },
  {
    id: "insider_lock_1",
    reportDate: "6:02am",
    time: "6:02am",
    timestamp: Date.now() - 7620000,
    symbol: "NVDA",
    companyName: "NVIDIA Corporation",
    trade: "Open Market Purchase Common Stock",
    member: "Jensen Huang",
    title: "President & CEO",
    premium: 15400000,
    premiumFormatted: "$15.4m",
    shares: 65000,
    price: 236.9,
    marketCap: "large",
    assetType: "stock",
    isLocked: true,
  },
  {
    id: "insider_lock_2",
    reportDate: "6:01am",
    time: "6:01am",
    timestamp: Date.now() - 7680000,
    symbol: "TSLA",
    companyName: "Tesla, Inc.",
    trade: "Grant of Stock Options",
    member: "Vaibhav Taneja",
    title: "Chief Financial Officer",
    premium: 4200000,
    premiumFormatted: "$4.20m",
    shares: 11000,
    price: 381.8,
    marketCap: "large",
    assetType: "stock",
    isLocked: true,
  },
  {
    id: "insider_lock_3",
    reportDate: "10/6 8:40pm",
    time: "8:40pm",
    timestamp: Date.now() - 41400000,
    symbol: "AAPL",
    companyName: "Apple Inc.",
    trade: "Purchase 25,000 Common Shares",
    member: "Arthur D Levinson",
    title: "Chair of the Board",
    premium: 5800000,
    premiumFormatted: "$5.80m",
    shares: 25000,
    price: 232.0,
    marketCap: "large",
    assetType: "stock",
    isLocked: true,
  },
];

export const RAW_CONGRESS_FLOW_ITEMS: CongressFlowItem[] = [
  {
    id: "cong_1",
    filingDate: "10/4/2026",
    transactionDate: "09/28/2026",
    time: "10/4 2:15pm",
    timestamp: Date.now() - 259200000,
    politician: "Nancy Pelosi",
    chamber: "House",
    party: "Democrat",
    state: "CA-11",
    symbol: "NVDA",
    assetDescription: "NVIDIA Corporation - Call Options (50 Contracts $180 Strike Exp 03/2027)",
    transaction: "Option Exercise",
    amountRange: "$1,000,001 - $5,000,000",
    estimatedPremium: 2500000,
    estimatedPremiumFormatted: "$2.50m",
  },
  {
    id: "cong_2",
    filingDate: "10/3/2026",
    transactionDate: "09/25/2026",
    time: "10/3 4:45pm",
    timestamp: Date.now() - 345600000,
    politician: "Michael McCaul",
    chamber: "House",
    party: "Republican",
    state: "TX-10",
    symbol: "MSFT",
    assetDescription: "Microsoft Corporation Common Stock",
    transaction: "Purchase",
    amountRange: "$500,001 - $1,000,000",
    estimatedPremium: 750000,
    estimatedPremiumFormatted: "$750k",
  },
  {
    id: "cong_3",
    filingDate: "10/2/2026",
    transactionDate: "09/22/2026",
    time: "10/2 11:30am",
    timestamp: Date.now() - 432000000,
    politician: "Ro Khanna",
    chamber: "House",
    party: "Democrat",
    state: "CA-17",
    symbol: "GOOGL",
    assetDescription: "Alphabet Inc. Class A Common Stock",
    transaction: "Purchase",
    amountRange: "$250,001 - $500,000",
    estimatedPremium: 350000,
    estimatedPremiumFormatted: "$350k",
  },
  {
    id: "cong_4",
    filingDate: "10/1/2026",
    transactionDate: "09/19/2026",
    time: "10/1 3:20pm",
    timestamp: Date.now() - 518400000,
    politician: "Tommy Tuberville",
    chamber: "Senate",
    party: "Republican",
    state: "AL",
    symbol: "PANW",
    assetDescription: "Palo Alto Networks Inc Common Stock",
    transaction: "Purchase",
    amountRange: "$100,001 - $250,000",
    estimatedPremium: 175000,
    estimatedPremiumFormatted: "$175k",
  },
  {
    id: "cong_5",
    filingDate: "09/30/2026",
    transactionDate: "09/15/2026",
    time: "9/30 9:10am",
    timestamp: Date.now() - 604800000,
    politician: "Dan Goldman",
    chamber: "House",
    party: "Democrat",
    state: "NY-10",
    symbol: "AAPL",
    assetDescription: "Apple Inc. Common Stock",
    transaction: "Sale",
    amountRange: "$50,001 - $100,000",
    estimatedPremium: 75000,
    estimatedPremiumFormatted: "$75k",
  },
  {
    id: "cong_lock_1",
    filingDate: "09/29/2026",
    transactionDate: "09/14/2026",
    time: "9/29 5:00pm",
    timestamp: Date.now() - 691200000,
    politician: "Markwayne Mullin",
    chamber: "Senate",
    party: "Republican",
    state: "OK",
    symbol: "RTX",
    assetDescription: "RTX Corporation Defense Systems",
    transaction: "Purchase",
    amountRange: "$250,001 - $500,000",
    estimatedPremium: 380000,
    estimatedPremiumFormatted: "$380k",
    isLocked: true,
  },
];

export function filterLiveFlowItems(
  items: LiveFlowItem[],
  filter: Partial<FlowFilterConfig>
): LiveFlowItem[] {
  return items.filter((item) => {
    // 1. Tickers
    if (filter.tickers && filter.tickers.length > 0) {
      const match = filter.tickers.some((t) => item.symbol.toUpperCase() === t.toUpperCase());
      if (!match) return false;
    }

    // 2. Minimum premium
    if (filter.minPremium && filter.minPremium > 0) {
      if (item.premium < filter.minPremium) return false;
    }

    // 3. Expiration / DTE
    if (filter.maxDte !== undefined && filter.maxDte < 9999) {
      if (item.dte > filter.maxDte) return false;
    }

    // 4. Sentiments
    if (filter.sentiments && filter.sentiments.length > 0) {
      if (!filter.sentiments.includes(item.sentiment)) return false;
    }

    // 5. Sides
    if (filter.sides && filter.sides.length > 0) {
      if (!filter.sides.includes(item.side)) return false;
    }

    // 6. Order types
    if (filter.orderTypes && filter.orderTypes.length > 0) {
      if (!filter.orderTypes.includes(item.type)) return false;
    }

    // 7. Asset types
    if (filter.assetTypes && filter.assetTypes.length > 0) {
      if (!filter.assetTypes.includes(item.assetType)) return false;
    }

    // 8. Market caps
    if (filter.marketCaps && filter.marketCaps.length > 0) {
      if (!filter.marketCaps.includes(item.marketCap)) return false;
    }

    // 9. Contract types (calls / puts / spreads)
    if (filter.contractTypes && filter.contractTypes.length > 0) {
      const isSpread = item.strategy.toLowerCase().includes("spread");
      const isCall = !isSpread && item.strategy.toLowerCase().includes("call");
      const isPut = !isSpread && item.strategy.toLowerCase().includes("put");
      let matchedType = false;
      if (filter.contractTypes.includes("calls") && isCall) matchedType = true;
      if (filter.contractTypes.includes("puts") && isPut) matchedType = true;
      if (filter.contractTypes.includes("spreads") && isSpread) matchedType = true;
      if (!matchedType) return false;
    }

    // 10. Checkboxes
    if (filter.isOtmOnly && !item.isOtm) return false;
    if (filter.volOverOiOnly && !item.volOverOi) return false;
    if (filter.upcomingEarningsOnly && !item.hasEarnings) return false;
    if (filter.aboveAskBelowBidOnly && !item.aboveAskBelowBid) return false;

    // 11. Numeric comparison: Underlying Price
    if (filter.priceValue !== null && filter.priceValue !== undefined) {
      if (filter.priceOperator === "less_than" && item.underlyingPrice >= filter.priceValue) return false;
      if (filter.priceOperator === "greater_than" && item.underlyingPrice <= filter.priceValue) return false;
    }

    // 12. Numeric comparison: Chance of profit
    if (filter.chanceValue !== null && filter.chanceValue !== undefined) {
      if (filter.chanceOperator === "less_than" && item.chance >= filter.chanceValue) return false;
      if (filter.chanceOperator === "greater_than" && item.chance <= filter.chanceValue) return false;
    }

    return true;
  });
}

export function filterNewsFlowItems(
  items: NewsFlowItem[],
  tickers: string[]
): NewsFlowItem[] {
  if (!tickers || tickers.length === 0) return items;
  return items.filter((item) =>
    item.symbols.some((sym) => tickers.some((t) => t.toUpperCase() === sym.toUpperCase()))
  );
}

export function filterInsiderFlowItems(
  items: InsiderFlowItem[],
  filter: { tickers?: string[]; insiderNames?: string[]; minPremium?: number; assetTypes?: string[]; marketCaps?: string[] }
): InsiderFlowItem[] {
  return items.filter((item) => {
    if (filter.tickers && filter.tickers.length > 0) {
      if (!filter.tickers.some((t) => t.toUpperCase() === item.symbol.toUpperCase())) return false;
    }
    if (filter.insiderNames && filter.insiderNames.length > 0) {
      const match = filter.insiderNames.some((n) => item.member.toLowerCase().includes(n.toLowerCase()));
      if (!match) return false;
    }
    if (filter.minPremium && filter.minPremium > 0) {
      if (item.premium < filter.minPremium) return false;
    }
    if (filter.assetTypes && filter.assetTypes.length > 0) {
      if (!filter.assetTypes.includes(item.assetType)) return false;
    }
    if (filter.marketCaps && filter.marketCaps.length > 0) {
      if (!filter.marketCaps.includes(item.marketCap)) return false;
    }
    return true;
  });
}

export function filterCongressFlowItems(
  items: CongressFlowItem[],
  filter: { tickers?: string[]; chamber?: string; party?: string }
): CongressFlowItem[] {
  return items.filter((item) => {
    if (filter.tickers && filter.tickers.length > 0) {
      if (!filter.tickers.some((t) => t.toUpperCase() === item.symbol.toUpperCase())) return false;
    }
    if (filter.chamber && filter.chamber !== "all") {
      if (item.chamber !== filter.chamber) return false;
    }
    if (filter.party && filter.party !== "all") {
      if (item.party !== filter.party) return false;
    }
    return true;
  });
}

export const BULLISH_FLOW_LEADERBOARD: FlowLeaderboardItem[] = [
  { symbol: "WMT", tradeCount: 27, premiumFormatted: "$15.27m", premiumRaw: 15270000, pctWidth: 82 },
  { symbol: "ARM", tradeCount: 56, premiumFormatted: "$18.43m", premiumRaw: 18430000, pctWidth: 86 },
  { symbol: "SPYM", tradeCount: 24, premiumFormatted: "$2.61m", premiumRaw: 2610000, pctWidth: 32 },
  { symbol: "NKE", tradeCount: 27, premiumFormatted: "$2.98m", premiumRaw: 2980000, pctWidth: 35 },
  { symbol: "LITE", tradeCount: 34, premiumFormatted: "$22.76m", premiumRaw: 22760000, pctWidth: 89 },
  { symbol: "CRWV", tradeCount: 59, premiumFormatted: "$23.06m", premiumRaw: 23060000, pctWidth: 90 },
  { symbol: "ORCL", tradeCount: 63, premiumFormatted: "$16.39m", premiumRaw: 16390000, pctWidth: 84 },
  { symbol: "NOK", tradeCount: 33, premiumFormatted: "$2.60m", premiumRaw: 2600000, pctWidth: 32 },
  { symbol: "GOOGL", tradeCount: 67, premiumFormatted: "$20.53m", premiumRaw: 20530000, pctWidth: 87 },
  { symbol: "/GF", tradeCount: 51, premiumFormatted: "$4.95m", premiumRaw: 4950000, pctWidth: 46 },
  { symbol: "NOW", tradeCount: 20, premiumFormatted: "$3.75m", premiumRaw: 3750000, pctWidth: 40 },
  { symbol: "ASTS", tradeCount: 28, premiumFormatted: "$5.01m", premiumRaw: 5010000, pctWidth: 47 },
  { symbol: "USO", tradeCount: 28, premiumFormatted: "$6.01m", premiumRaw: 6010000, pctWidth: 52 },
  { symbol: "ECHO", tradeCount: 10, premiumFormatted: "$6.54m", premiumRaw: 6540000, pctWidth: 54 },
  { symbol: "XSP", tradeCount: 84, premiumFormatted: "$17.64m", premiumRaw: 17640000, pctWidth: 85 },
  { symbol: "RKLB", tradeCount: 33, premiumFormatted: "$4.40m", premiumRaw: 4400000, pctWidth: 43 },
  { symbol: "NFLX", tradeCount: 21, premiumFormatted: "$3.02m", premiumRaw: 3020000, pctWidth: 36 },
  { symbol: "CNC", tradeCount: 9, premiumFormatted: "$2.61m", premiumRaw: 2610000, pctWidth: 32 },
  { symbol: "IWM", tradeCount: 146, premiumFormatted: "$55.96m", premiumRaw: 55960000, pctWidth: 100 },
  { symbol: "ASML", tradeCount: 9, premiumFormatted: "$20.10m", premiumRaw: 20100000, pctWidth: 87 },
];

export const BEARISH_FLOW_LEADERBOARD: FlowLeaderboardItem[] = [
  { symbol: "ETHA", tradeCount: 116, premiumFormatted: "$7.05m", premiumRaw: 7050000, pctWidth: 48 },
  { symbol: "/HE", tradeCount: 36, premiumFormatted: "$6.23m", premiumRaw: 6230000, pctWidth: 44 },
  { symbol: "U", tradeCount: 37, premiumFormatted: "$5.38m", premiumRaw: 5380000, pctWidth: 41 },
  { symbol: "SKHY", tradeCount: 41, premiumFormatted: "$13.43m", premiumRaw: 13430000, pctWidth: 62 },
  { symbol: "SDGR", tradeCount: 18, premiumFormatted: "$3.56m", premiumRaw: 3560000, pctWidth: 32 },
  { symbol: "ETHE", tradeCount: 18, premiumFormatted: "$349k", premiumRaw: 349000, pctWidth: 18 },
  { symbol: "XLU", tradeCount: 19, premiumFormatted: "$7.13m", premiumRaw: 7130000, pctWidth: 49 },
  { symbol: "HIVE", tradeCount: 15, premiumFormatted: "$559k", premiumRaw: 559000, pctWidth: 20 },
  { symbol: "EBAY", tradeCount: 26, premiumFormatted: "$1.57m", premiumRaw: 1570000, pctWidth: 26 },
  { symbol: "LABU", tradeCount: 32, premiumFormatted: "$4.89m", premiumRaw: 4890000, pctWidth: 39 },
  { symbol: "XBI", tradeCount: 15, premiumFormatted: "$4.98m", premiumRaw: 4980000, pctWidth: 40 },
  { symbol: "NU", tradeCount: 41, premiumFormatted: "$6.26m", premiumRaw: 6260000, pctWidth: 45 },
  { symbol: "TLT", tradeCount: 16, premiumFormatted: "$31.31m", premiumRaw: 31310000, pctWidth: 78 },
  { symbol: "BA", tradeCount: 11, premiumFormatted: "$7.01m", premiumRaw: 7010000, pctWidth: 48 },
  { symbol: "EWY", tradeCount: 34, premiumFormatted: "$15.25m", premiumRaw: 15250000, pctWidth: 66 },
  { symbol: "AAPL", tradeCount: 202, premiumFormatted: "$34.77m", premiumRaw: 34770000, pctWidth: 81 },
  { symbol: "GEV", tradeCount: 15, premiumFormatted: "$11.90m", premiumRaw: 11900000, pctWidth: 59 },
  { symbol: "NVDA", tradeCount: 373, premiumFormatted: "$172.13m", premiumRaw: 172130000, pctWidth: 100 },
  { symbol: "MKL", tradeCount: 12, premiumFormatted: "$716k", premiumRaw: 716000, pctWidth: 22 },
  { symbol: "MUU", tradeCount: 12, premiumFormatted: "$3.10m", premiumRaw: 3100000, pctWidth: 30 },
];

export function calculateFlowSummary(items: LiveFlowItem[]): FlowSummary {
  let callPremium = 0;
  let putPremium = 0;
  let sweepCount = 0;
  let blockCount = 0;

  const symbolCalls: Record<string, { premium: number; count: number }> = {};
  const symbolPuts: Record<string, { premium: number; count: number }> = {};

  for (const item of items) {
    if (item.type === "SWEEP") sweepCount++;
    if (item.type === "BLOCK") blockCount++;

    const isCall = item.strategy.toLowerCase().includes("call");
    const isPut = item.strategy.toLowerCase().includes("put");

    if (isCall) {
      callPremium += item.premium;
      if (!symbolCalls[item.symbol]) symbolCalls[item.symbol] = { premium: 0, count: 0 };
      symbolCalls[item.symbol].premium += item.premium;
      symbolCalls[item.symbol].count += 1;
    } else if (isPut) {
      putPremium += item.premium;
      if (!symbolPuts[item.symbol]) symbolPuts[item.symbol] = { premium: 0, count: 0 };
      symbolPuts[item.symbol].premium += item.premium;
      symbolPuts[item.symbol].count += 1;
    }
  }

  const totalPremium = callPremium + putPremium;
  const bullishSentimentRatio = totalPremium > 0
    ? Math.round((callPremium / totalPremium) * 100)
    : 50;

  const topBullishSymbols = Object.entries(symbolCalls)
    .map(([symbol, data]) => ({ symbol, callPremium: data.premium, tradeCount: data.count }))
    .sort((a, b) => b.callPremium - a.callPremium)
    .slice(0, 6);

  const topBearishSymbols = Object.entries(symbolPuts)
    .map(([symbol, data]) => ({ symbol, putPremium: data.premium, tradeCount: data.count }))
    .sort((a, b) => b.putPremium - a.putPremium)
    .slice(0, 6);

  const largestTrades = [...items]
    .sort((a, b) => b.premium - a.premium)
    .slice(0, 5);

  return {
    totalTrades: items.length,
    totalPremium,
    callPremium,
    putPremium,
    bullishSentimentRatio,
    sweepCount,
    blockCount,
    topBullishSymbols,
    topBearishSymbols,
    bullishLeaderboard: BULLISH_FLOW_LEADERBOARD,
    bearishLeaderboard: BEARISH_FLOW_LEADERBOARD,
    largestTrades,
  };
}
