import { useAgent } from "agents/react";
import { useAgentChat } from "@cloudflare/ai-chat/react";
import { useState } from "react";
interface User { login: string; name: string; avatar: string; }
function textOf(message: any) { return typeof message.content === "string" ? message.content : message.parts?.filter((p: any) => p.type === "text").map((p: any) => p.text).join("") || ""; }
export function Chat({ user }: { user: User }) {
  const [mode, setMode] = useState<"chat" | "nlq">("chat"); const [input, setInput] = useState(""); const [queryResult, setQueryResult] = useState<any>(null); const [querying, setQuerying] = useState(false);
  const agent = useAgent({ agent: "SearchAgent", name: user.login }); const { messages, sendMessage, status } = useAgentChat({ agent });
  const submitChat = (e: React.FormEvent) => { e.preventDefault(); if (input.trim() && status === "ready") { sendMessage({ text: input }); setInput(""); } };
  const submitNLQ = async (e: React.FormEvent) => { e.preventDefault(); if (!input.trim()) return; setQuerying(true); setQueryResult(null); try { const response = await fetch("/api/nlq", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query: input }) }); setQueryResult(await response.json()); } finally { setQuerying(false); } };
  return <div className="app"><header><h1>🤖 Multi-Agent Assistant</h1><nav><button className={mode === "chat" ? "active" : ""} onClick={() => setMode("chat")}>💬 Chat & actions</button><button className={mode === "nlq" ? "active" : ""} onClick={() => setMode("nlq")}>📊 Query messages</button></nav><div className="user-info"><img src={user.avatar} alt={user.login}/><span>{user.name}</span><a href="/auth/logout" className="logout">Logout</a></div></header>
    {mode === "chat" ? <><div className="messages">{messages.length === 0 && <div className="welcome"><h2>Ask anything</h2><p>The orchestrator delegates to search, payments, and task sub-agents.</p></div>}{messages.map((msg: any) => <div key={msg.id} className={`message ${msg.role}`}><div className="msg-content">{textOf(msg)}{msg.role === "assistant" && msg.parts?.filter((p: any) => p.type !== "text").map((p: any, i: number) => <details key={i} className="tool-call"><summary>🔧 {p.type}</summary><pre>{JSON.stringify(p.output ?? p.result ?? p.input ?? {}, null, 2)}</pre></details>)}</div></div>)}{status === "streaming" && <div className="typing">Thinking…</div>}</div><form className="input-area" onSubmit={submitChat}><input value={input} onChange={e => setInput(e.target.value)} placeholder="Ask, search, draft a task, or prepare a payment…" disabled={status !== "ready"}/><button type="submit" disabled={!input.trim() || status !== "ready"}>Send</button></form></> : <><section className="nlq"><h2>Query durable-object conversation messages</h2><p>Read-only NLQ: search, count, filter by role, and inspect message history. It cannot invoke action tools.</p><form className="input-area" onSubmit={submitNLQ}><input value={input} onChange={e => setInput(e.target.value)} placeholder="e.g. count assistant messages about onboarding" disabled={querying}/><button type="submit" disabled={!input.trim() || querying}>Run query</button></form>{queryResult && <pre className="results">{JSON.stringify(queryResult, null, 2)}</pre>}</section></>}
  </div>;
}
